apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podinfo
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
